server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AccountDB
    username: account
    password: account
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
   # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  application:
    name: ACCOUNT-SERVICE
      